name = "hitit-cyber-club"
main = "src/index.js"
compatibility_date = "2026-09-22"

[vars]
ADMIN_PASSWORD = "change-me-before-deploy"

[[kv_namespaces]]
binding = "CYBER_DATA"
id = "3859d61b864141f3b7e9ba546d2b28b2"

[assets]
directory = "./public"
binding = "ASSETS"
